config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :credentials, path_names: { new: 'upload' } do
    collection do
      get :key_info
      post :edit_multiple
      put :update_multiple
    end
  end

  controller :application do
    get '/authorized_keys/:username(/:host)' => :authorized_keys, host: %r{[^\/]+}, as: :authorized_keys
    post '/register/:host' => :register_host, host: %r{[^\/]+}, as: :register_host
    get '/x-tree/F5Monitor' => :f5_health_check, defaults: { format: :html } if ENV['F5_HEALTHCHECK']
  end

  root 'credentials#index'
end

app/models/credential.rb
require 'sshkey'
# SSH Credential class
class Credential < ActiveRecord::Base
  acts_as_taggable

  EXPIRED_AGE = 365
  EXPIRING_AGE = 305

  belongs_to :user
  before_validation :normalize_data

  validates :public_key, :user, :username, presence: true
  validates :username, format: /\A[a-z0-9_]+\z/
  validate :public_key_rfc4716, if: :public_key?
  validate :resolv_host, unless: :default_key?
  validates :host, format: { without: /[A-Z]/ } unless :default_key?

  def self.public_keys_for(username, host = nil)
    Credential.where(username: username, host: [host, nil]).pluck('DISTINCT public_key')
  end

  def self.key_info?(key)
    info = { valid: key_valid?(key) }
    info.merge!(bits: key_bits(key), fingerprint: key_fingerprint(key)) if info[:valid]
    info
  end

  def default_key?
    !host?
  end

  def host
    host? ? self[:host] : I18n.t('activerecord.values.credential.host.blank')
  end

  def self.key_valid?(key)
    SSHKey.valid_ssh_public_key? key
  end

  def expire_at
    created_at + EXPIRED_AGE.days
  end

  def expired?
    created_at < EXPIRED_AGE.days.ago
  end

  def expiring?
    (created_at < EXPIRING_AGE.days.ago) && !expired?
  end

  def nonexpired?
    !expired?
  end

  def logon
    "#{username}@#{host}"
  end

  def status
    if expired?
      'Expired'
    elsif expiring?
      'Expiring'
    else
      'Valid'
    end
  end

  def expiration_percentage(time = Time.zone.now)
    if expired?
      100
    else
      ((time - created_at) / (expire_at - created_at) * 100).round
    end
  end

  def copy_text_attr
    :public_key
  end

  private

  def normalize_data
    self[:host] = nil if host.eql? I18n.t('activerecord.values.credential.host.blank')
    self[:host] = host.to_s.downcase unless default_key?
    self[:username] = username.to_s.downcase
    self[:public_key] = public_key
                        .to_s
                        .encode('ASCII', invalid: :replace, undef: :replace, replace: '')
                        .strip
                        .gsub(/(\n|\r)/, '')
  end

  def self.key_bits(key)
    SSHKey.ssh_public_key_bits(key) if self.key_valid?(key)
  end

  def self.key_fingerprint(key)
    SSHKey.md5_fingerprint(key) if self.key_valid?(key)
  end

  def public_key_rfc4716
    errors.add(:public_key, 'is not valid') unless self.class.key_valid?(public_key)
  end

  def resolv_host
    errors.add(:host, 'does not resolve') unless resolv? host
  end

  def resolv?(hostname)
    true if Resolv.getaddress hostname
  rescue Resolv::ResolvError
    false
  end
end

app/controllers/credentials_controller.rb
# Credential controller
class CredentialsController < ApplicationController
  respond_to :html, :xml, :json, :js, :datatable
  before_action :set_credentials, if: :user_signed_in?
  before_action :set_credential, only: [:index, :show, :new, :edit, :update, :destroy]
  after_action :delete_key_cache_for, only: [:create, :update, :destroy]
  responders :flash, :http_cache

  # GET /credentials.format
  def index
    respond_with @credentials do |format|
      format.datatable { render json: CredentialsDatatable.new(view_context, collection: @credentials) }
    end
  end

  # GET /credentials/1.format
  def show
    respond_with @credential
  end

  # GET /credentials/new.format
  def new
    respond_with @credential
  end

  # GET /credentials/1/edit.format
  def edit
  end

  # POST /credentials/edit_multiple.format
  def edit_multiple
    if params[:delete]
      delete_key_cache_for @credentials.map(&:destroy)
      flash[:notice] = "Successfully destroyed #{t :credential_with_count, count: @credentials.count}"
      render :destroy_multiple
    else
      @credential = @credentials.first
    end
  end

  # POST /credentials.format
  def create
    @credential = @credentials.create credential_params
    respond_with @credential, location: -> { credential_path(@credential) }
  end

  # PATCH/PUT /credentials/1.format
  def update
    @credential.update credential_params
    respond_with @credential
  end

  # PATCH/PUT /credentials/update_multiple.format
  def update_multiple
    update_params = credential_params.reject { |_k, v| v.blank? }
    errors = @credentials.reject { |credential| credential.update(update_params) }
    @credential = errors.empty? ? @credentials.first : errors.first
    delete_key_cache_for @credentials
    respond_with @credential,
                 location: credentials_url,
                 action: :edit_multiple,
                 notice: "Successfully updated #{t :credential_with_count, count: @credentials.count}"
  end

  # DELETE /credentials/1.format
  def destroy
    @credential.destroy
    respond_with @credential
  end

  # GET /credentials/key_info/:key
  def key_info
    @key_info = Credential.key_info? params[:key]
    respond_with @key_info
  end

  private

  # Get collection
  def set_credentials
    @credentials = current_user.credentials
    @default_new_credential = @credentials.all.new username: current_user.username
    @credentials = @credentials.find(params[:ids]) if params.key?(:ids)
  end

  # Get current object from collection
  def set_credential
    @credential = params.key?(:id) ? @credentials.find(params[:id]) : @default_new_credential
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def credential_params
    # merge in the current_user object so that user's can't inject other user's IDs
    params.require(:credential).permit(:public_key, :host, :username, :tag_list).merge(user: current_user)
  end

  def delete_key_cache_for(cache = nil)
    cache ||= [@credential]
    cache.each do |credential|
      Rails.cache.delete [credential.username, credential.host]
    end
  end
end

app/helpers/credentials_helper.rb
# Helper methods for Credentials controller
module CredentialsHelper
  def credential_status_class(credential)
    if credential.expired?
      'danger'
    elsif credential.expiring?
      'warning'
    else
      'success'
    end
  end

  def multiple_edit_checkbox(credential)
    button_tag(bs_icon('unchecked'), class: 'row-selector btn btn-default', type: :button) +
      check_box_tag('ids[]', credential.id, false, class: 'hidden')
  end

  def credential_status_label(credential)
    dtg_span(credential.created_at, :hidden) +
      content_tag(:span, credential.status, class: "label label-#{credential_status_class(credential)}")
  end

  def ssh_key_span(key)
    key_with_spaces = key.to_s.scan(/.{1,70}/).join('&#8203;').html_safe
    content_tag :span,
                truncate(key, length: 43),
                class: 'ssh-key',
                data: { toggle: :popover, trigger: :click, content: key_with_spaces, placement: :bottom }
  end

  def key_info(key)
    content_tag(:div, id: 'key-info', class: 'help-block') do
      if Credential.key_valid? key
        content_tag(:div, class: 'text-success') do
          "#{Credential.key_bits key} Bits - MD5 fingerprint: #{Credential.key_fingerprint key}"
        end
      elsif key
        content_tag(:div, 'is not valid', class: 'text-danger')
      end
    end
  end

  def duration_left(credential)
    credential.expired? ? '&mdash;'.html_safe : time_ago_in_words(credential.expire_at)
  end

  def expiration(credential)
    dtg_span(credential.created_at, :hidden) +
      content_tag(:span, duration_left(credential), class: 'duration-left')
  end

  # def expiration_progress(credential)
  #   percentage, expire_at = credential.expiration_percentage, credential.expire_at
  #   css_class = %W(progress-bar progress-bar-#{credential_status_class(credential)})
  #   css_class << %w(progress-bar-striped active) unless credential.expired?
  #   dtg_span(expire_at, :hidden) + content_tag(:div, class: :progress) do
  #     content_tag :div, nil,
  #                 class: css_class,
  #                 style: "width: #{percentage}%",
  #                 role: :progressbar, aria: { valuenow: percentage, valuemin: 0, valuemax: 100 }
  #   end + duration_left(credential)
  # end
end

app/views/credentials/_form.html.haml
:ruby
  remote ||= false
  disable_with_text = t('helpers.submit.saving', model: @credential.model_name.human)
= bootstrap_form_for @credential, remote: remote do |f|
  = f.alert_message 'Errors in saving', error_summary: !remote
  = f.text_field :username
  = f.text_field :host, placeholder: I18n.t('activerecord.values.credential.host.blank')
  = f.text_field :tag_list,
                 value: @credential.tag_list.to_s,
                 class: :tokenize,
                 icon: 'tags',
                 help: t('helpers.tag_list_help_html')

  = f.text_area :public_key, data: { source: key_info_credentials_path(format: :json) }, rows: 5
  = key_info @credential.public_key

  .actions{ class: ('modal-footer' if remote) }
    - if remote
      .spinner.hidden
    = f.button data: { disable_with: disable_with_text }, class: 'btn btn-primary'
    - if remote
      %button.btn.btn-default{ type: :button, data: { dismiss: :modal, empty: :modal } } Cancel
    - else
      \|
      = link_to 'Cancel', :back, class: 'btn btn-default'

app/views/credentials/_multiple_form.html.haml
:ruby
  remote ||= false
  button_label = t :'helpers.submit.update', model: t(:credential_with_count, count: @credentials.count)
  disable_with_text = t :'helpers.submit.saving', model: t(:credential_with_count, count: @credentials.count)
= bootstrap_form_for @credential, url: update_multiple_credentials_path, method: :put, remote: remote do |f|
  = f.alert_message 'Errors in updating', error_summary: !remote
  .list-group
    .list-group-item.active
      %h4.list-group-item-heading= Credential.human_attribute_name :host, count: @credentials.count
    - @credentials.each do |credential|
      .list-group-item{ class: "list-group-item-#{credential_status_class(credential)}" }
        = credential_status_label(credential)
        = credential.logon
        = hidden_field_tag 'ids[]', credential.id

  = f.text_area :public_key, data: { source: key_info_credentials_path(format: :json) }, rows: 5
  = key_info @credential.public_key

  .actions{ class: ('modal-footer' if remote) }
    - if remote
      .spinner.hidden
    = f.button button_label, data: { disable_with: disable_with_text }, class: 'btn btn-primary'
    - if remote
      %button.btn.btn-default{ type: :button, data: { dismiss: :modal } } Cancel
    - else
      \|
      = link_to 'Cancel', :back, class: 'btn btn-default'

app/views/credentials/_status_area.html.haml
- grouped_by_status = current_user.credentials.group_by(&:status)
.col-lg-4.col-md-4.col-sm-4.col-xs-12
  %h5.text-muted= current_user.model_name.human
  %p.h3= current_user.full_name
.col-lg-2.col-md-2.col-sm-2.col-xs-3
  %h5.text-muted Total
  %p.h3
    %span.label.label-default= current_user.credentials.count
- [%w(Valid success), %w(Expiring warning), %w(Expired danger)].each do |status, label_class|
  .col-lg-2.col-md-2.col-sm-2.col-xs-3
    %h5.text-muted= status
    %p.h3
      %span.label{ class: "label-#{label_class}" }= grouped_by_status.fetch(status, []).count

app/views/credentials/edit.html.haml
%h1 Editing #{@credential.model_name.human}

= render 'form'

app/views/credentials/edit_multiple.html.haml
%h1 Editing #{@credential.model_name.human count: @credentials.count}

= render 'multiple_form'

app/views/credentials/index.html.haml
:ruby
  model_name = @credentials.model_name.human
  create_title   = t :'helpers.submit.credential.create', model: model_name, default: :'helpers.submit.create'
  update_title   = t :'helpers.submit.credential.update', model: model_name, default: :'helpers.submit.update'
  multiple_title = update_title.pluralize
  table_css_data = { datatable_dom: 'frt', source: credentials_path(:datatable), resourcename: model_name }

.row#status-area= render 'status_area'

= form_tag edit_multiple_credentials_path, remote: true do
  %table.table.table-hover#credential-table{ width: '100%', data: table_css_data }
    %thead
      %tr
        %th{ data: { orderable: 'false' } }
          = button_tag bs_icon_and_text('unchecked', t(:'helpers.labels.all')),
                       class: 'btn btn-default',
                       id: 'toggle-checkboxes',
                       type: :button,
                       data: { context: '#credential-table tbody', state: false }
        %th= Credential.human_attribute_name :status
        %th= Credential.human_attribute_name :expires
        %th= Credential.human_attribute_name :username
        %th= Credential.human_attribute_name :host
        %th{ data: { orderable: 'false' } }= Credential.human_attribute_name :tag_list
        %th{ data: { orderable: 'false' } }= t :'helpers.labels.actions'
        %th.never= Credential.human_attribute_name :public_key
    %tbody

  %hr

  #toolbar{ data: { spy: 'affix', offset_bottom: 90 } }
    = link_to bs_icon_and_text('upload', create_title),
              new_credential_path,
              class: 'btn btn-primary pull-right',
              data: { toggle: :modal, target: '#create-form-modal' },
              remote: true

    %span#multiple-count 0
    %span<
      %span>= model_name
      %span#multiple-plural s
      selected
    = button_tag bs_icon_and_text('edit', t('helpers.submit.update', model: 'Public key')),
      class: 'btn btn-default disabled update-multiple',
      data: { toggle: :modal, target: '#multiple-form-modal' }
    \|
    = button_tag bs_icon_and_text('trash', t(:'helpers.links.destroy', default: 'Destroy')),
      class: 'btn btn-danger disabled update-multiple',
      id: 'multiple-delete',
      name: :delete,
      data: { confirm: 'Are you sure?' }

= render layout: 'modal', locals: { id: 'create-form-modal', title: create_title, footer: false } do
  .spinner.center-block
= render layout: 'modal', locals: { id: 'update-form-modal', title: update_title, footer: false } do
  .spinner.center-block
= render layout: 'modal', locals: { id: 'multiple-form-modal', title: multiple_title, footer: false } do
  .spinner.center-block

app/views/credentials/key_info.html.haml
- if @key_info[:valid]
  = field_with_value 'Valid', @key_info[:valid]
  = field_with_value 'Bits', @key_info[:bits]
  = field_with_value 'Valid', @key_info[:fingerprint]
- else
  .text-warning Could not determine key type/invalid key

app/views/credentials/new.html.haml
%h1 New #{@credential.model_name.human}

= render 'form'

app/views/credentials/show.html.haml
= field_with_value 'User', mail_to_user(@credential.user)
= field_with_value 'Host', @credential.host
= field_with_value 'Public Key', @credential.public_key
= field_with_value 'Created', @credential.created_at
= field_with_value 'Updated', @credential.updated_at

%hr
.row
  .col-md-offset-2
    = link_to bs_icon_and_text('pencil', 'Edit'), edit_credential_path(@credential), class: 'btn btn-success'
    \|
    = link_to 'List All Credentials', credentials_path, class: 'btn btn-default'