config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :credentials, path_names: { new: 'upload' } do
    collection do
      get :key_info
      post :edit_multiple
      put :update_multiple
    end
  end

  controller :application do
    get '/authorized_keys/:username(/:host)' => :authorized_keys, host: %r{[^\/]+}, as: :authorized_keys
    post '/register/:host' => :register_host, host: %r{[^\/]+}, as: :register_host
    get '/x-tree/F5Monitor' => :f5_health_check, defaults: { format: :html } if ENV['F5_HEALTHCHECK']
  end

  root 'credentials#index'
end

app/controllers/application_controller.rb
require 'application_responder'

# Methods visible to all controllers
class ApplicationController < ActionController::Base
  rescue_from DeviseLdapAuthenticatable::LdapException, with: :show_ldap_error
  rescue_from Net::LDAP::LdapError, with: :show_ldap_error
  self.responder = ApplicationResponder
  respond_to :html
  layout false, only: :authorized_keys

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  before_action :authenticate_user!, except: [:f5_health_check, :authorized_keys, :register_host]

  def f5_health_check
    render html: 'THE SERVER IS UP'.html_safe
  end

  # GET /authorized_keys/?username=:username&host=:host
  def authorized_keys
    @start_time = Time.zone.now
    @cached = Rails.cache.exist? [params[:username], params[:host]]
    @authorized_keys = fetch_authorized_keys_from_cache params[:username], params[:host]
    respond_to :text, :json, :html
  end

  def register_host
    @host = Host.where(fqdn: params[:host]).first_or_create
    save_host_taggings
  ensure
    head @host.save ? :ok : :unprocessable_entity
  end

  protected

  def show_ldap_error(exception)
    render text: exception, status: 500
  end

  def fetch_authorized_keys_from_cache(username, host)
    Rails.cache.fetch [username, host],  expires_in: 10.seconds do
      Credential.public_keys_for(username, host).to_a
    end
  end

  def append_info_to_payload(payload)
    super
    payload[:user_id] = current_user.try :username
    payload[:session_id] = session.id
  end

  def save_host_taggings
    @host.taggings.destroy_all
    if (payload = JSON.parse(request.raw_post))
      payload.each do |context, tags|
        @host.set_tag_list_on context, tags
      end
    end
  rescue JSON::ParserError
    Rails.logger.warn "Error parsing JSON payload during registration of #{@host.fqdn}"
  end
end

app/helpers/application_helper.rb
# Global helper methods for all controller
module ApplicationHelper
  include BootstrapHelper

  SHOW_LINK_IN_CRUD = false
  ICON_ONLY = true
  local_env = Rails.env.development? || Rails.env.test?
  REVISIONS_LOG = Rails.root.join(local_env ? 'test/fixtures' : '../..', 'revisions.log')

  def action_btns_for(object)
    content_tag(:div, copy_button_for(object, 'btn btn-info'), class: 'btn-group') +
      '&nbsp;'.html_safe +
      crud_btns_for(object)
  end

  def crud_btns_for(object, group = true)
    css_class = 'btn-group' if group
    content_tag :div, class: css_class do
      concat show_link_for(object, 'btn btn-default') if SHOW_LINK_IN_CRUD
      concat edit_link_for(object, 'btn btn-default')
      concat destroy_link_for(object, 'btn btn-danger')
    end
  end

  def field_with_value(field_name, value, size = 'md')
    content_tag :div, class: :row do
      concat content_tag(:div, content_tag(:strong, field_name), class: "col-#{size}-2 text-right")
      concat content_tag(:div, value, class: "col-#{size}-4")
    end
  end

  def crud_dropdown_btn_for(object, css_classes = nil)
    content_tag :div, class: [*css_classes].push(:dropdown) do
      bs_dropdown_button_with_text + content_tag(:ul, class: 'dropdown-menu dropdown-menu-right') do
        concat content_tag(:li, show_link_for(object)) if SHOW_LINK_IN_CRUD
        concat content_tag(:li, edit_link_for(object))
        concat content_tag(:li, destroy_link_for(object, 'bg-danger'))
      end
    end
  end

  def show_link_for(object, css_class = nil)
    text = ICON_ONLY ? nil : t(:'helpers.links.show', default: 'Show')
    link_to bs_icon_and_text('sunglasses', text),
            object,
            remote: true,
            class:  [*css_class].push('show-link')
  end

  def copy_button_for(object, css_class = nil)
    return nil unless object.respond_to?(:copy_text_attr)
    name  = object.class.human_attribute_name object.copy_text_attr
    button_tag bs_icon_and_text('copy', ICON_ONLY ? nil : t(:'helpers.links.copy', default: 'Copy')),
               data: {
                 clipboard_text: object[object.copy_text_attr],
                 copied_hint: "Copied #{name}!",
                 copy_hint: "Copy #{name} to clipboard"
               },
               type: :button,
               class: [*css_class].push('copy-link')
  end

  def edit_link_for(object, css_class = nil)
    text = ICON_ONLY ? nil : t(:'helpers.links.edit', default: 'Edit')
    link_to bs_icon_and_text('pencil', text),
            [:edit, object],
            remote: true,
            class: [*css_class].push('edit-link')
  end

  def destroy_link_for(object, css_class = nil)
    text = ICON_ONLY ? nil : t(:'helpers.links.destroy', default: 'Destroy')
    link_to bs_icon_and_text('trash', text),
            object,
            method: :delete,
            remote: true,
            class:  [*css_class].push('destroy-link'),
            data: { confirm: 'Are you sure?' }
  end

  def mail_to_user(user)
    mail_to(user.email, user.full_name)
  end

  def dtg_span(time, css_class = [])
    content_tag :span,
                time,
                class: [*css_class] << 'datetimegroup',
                data: {
                  order: time.to_i,
                  time: time.iso8601
                }
  end

  def gravatar(user, size = 40)
    image_tag "https://secure.gravatar.com/avatar/#{user.gravatar_hash}?s=#{size}&d=mm&r=g"
  end

  def capistrano_deployment_revision
    return unless File.exist? REVISIONS_LOG
    # eg "Branch master (at 820516a) deployed as release 20150513185431 by jenkins"
    message = IO.readlines(REVISIONS_LOG)[-1]
    branch, tags, release = message.split(/^Branch (.+?) \(at (.+?)\) deployed as release (\d+?) .+$/)[1..-1]
    release = Time.utc(*release.split(/(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/)[1..-1])
    [
      bold_field('Branch: ', branch),
      bold_field('Tags: ', tags),
      bold_field('Release: ', release)
    ].join(' / ').html_safe
  end

  def bold_field(field, value)
    content_tag(:span, content_tag(:b, field) + value)
  end
end

app/views/application/_flash_messages.html.haml
- if notice
  = bs_alert('info') do
    %span.glyphicon.glyphicon.glyphicon-info-sign{ 'aria-hidden' => :true }
    %strong Notice:
    = notice
- if alert
  = bs_alert('danger') do
    %span.glyphicon.glyphicon.glyphicon-alert{ 'aria-hidden' => :true }
    %strong Error!
    = alert

app/views/application/_footer.html.haml
%footer
  .container-fluid
    .row
      .col-lg-6.col-md-6.col-sm-6
        - if ENV['COPYRIGHT_NOTICE']
          %p
            &copy; 2014 &ndash;
            = Time.now.year
            = ENV['COPYRIGHT_NOTICE']
      .col-lg-6.col-md-6.col-sm-6
        %p.text-right
          - if ENV['INFO_SECURITY_LEVEL'] && ENV['INFO_SECURITY_URL']
            %p
              Information Security:
              = link_to ENV['INFO_SECURITY_LEVEL'], ENV['INFO_SECURITY_URL']
          %p
            %span
              %b Version:
              v#{SSHKeyManager::Application::VERSION}
            - if ENV['BUILD_NUMBER']
              \/
              = bold_field('Build: ', "##{ENV['BUILD_NUMBER']}")
          %p
            - cache 'revision' do
              = capistrano_deployment_revision

app/views/application/_header.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ data: { target: '#sshkm-navbar', toggle: :collapse }, type: :button }
        %span.sr-only Toggle navigation
        - 3.times do
          %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = image_tag 'brand.png', alt: 'SSHKM', height: 40
    .collapse.navbar-collapse#sshkm-navbar
      %ul.nav.navbar-nav.navbar-left
        = bs_nav_link_to 'Credentials', credentials_path, active: { controller: 'credentials' }
        %li
          %a{ href: '/docs' } Docs
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to bs_icon_and_text('question-sign', 'Help'), '#'
        - unless devise_controller?
          %li.dropdown
            %a.gravatar.dropdown-toggle{ aria: { expanded: false }, data: { toggle: :dropdown }, href: '#', role: :button }
              = current_user.username
              = gravatar current_user
              %span.caret
            %ul.dropdown-menu{ role: :menu }
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete

app/views/application/_modal.html.haml
.modal.fade{ role: :dialog, tabindex: '-1', id: id }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ type: :button, data: { dismiss: :modal } } &times;
        %h4.modal-title= title
      .modal-body
        = yield
      - if footer
        .modal-footer
          %button.btn.btn-warning{ type: :button, data: { dismiss: :modal } } Cancel

app/views/application/_panel.html.haml
- type ||= 'default'
.panel{ id: id, class: "panel-#{type}" }
  .panel-heading
    %h2.panel-title= title
  .panel-body
    = yield

app/views/application/_session_links.html.haml
- if user_signed_in?
  = link_to "Logout #{current_user.username}",
            destroy_user_session_path,
            method: :delete,
            class: 'btn btn-warning pull-right'
- else
  = link_to 'Login',
            new_user_session_path,
            class: 'btn btn-success pull-right'

app/views/application/authorized_keys.html.haml
.row
  %span # --- #{ Rails.env } mode /
  %span cache: #{ @cached ? 'hit' : 'miss' } /
  %span response: #{ Time.zone.now - @start_time }s /
  %span keys: #{ @authorized_keys.count }
- @authorized_keys.each do |key|
  .row= key